### ISSUE TITLE
Fix Documentation & Helpful Errors

### ISSUE THREAD

**Issue by JWiley** [JWiley/brmsmargins#3]
Thanks to feedback / suggestions from @jwilliamrozelle several priority areas to improve are:

- [x] fix documentation for `brmsmargins()` that misleading suggests both `at` and `add` are optional when at least one is required
- [ ] ensure documentation for `brmsmargins()` and `prediction()` are clear (& check for) which arguments are required vs. optional
- [x] add helpful errors for all required arguments in `brmsmargins()`
- [x] add helpful errors for arguments in `prediction()`

**Comment by jwrozelle** [comment]
Hope all is well there! Since this was so minor, I just added the error message in myself and submitted a pull request. 

Also happy to contribute tests, errors, or anything else on the R programming side if you'd find it helpful so that you can focus on other things in the package. I'm not proficient in C++, and wouldn't want to tinker with any of the actual calculations, but, know my way around package development essentials.

**Comment by JWiley** [comment]
@jwilliamrozelle Thanks, I appreciate that. I've also pushed some more changes today with some further messages around arguments to hopefully make issues easier.

I'd definitely welcome any contributions around tests, errors, docs, or any other package improvements and would of course recognize contributions/authorship if you did. I have three bigger tasks in mind for the package, in no particular order:

- support for multivariate models / univariate models where predictions have multiple levels (like ordinal, multinomial outcomes)
- conduct a more extensive simulation study to evaluate performance and conditions impacting bias, etc.
- support for non normal random effect distributions (first up being t distribution, which can be quite helpful for heavier tailed random effect distributions and is supported nicely by `brms` already)

I don't think it would have to be huge work but something else I wonder about is more "convenience" functions. Nice output, graphs, etc.  I've not thought too much about the output format so far and what people do with the output once they have it so believe there is probably room for improvement there & would definitely be on the `R` side of things.

**Comment by JWiley** [comment]
Done now in v0.2.0

**Comment by jwrozelle** [comment]
Whoops, looks like I missed this. Happy to touch base at some point if I can help on any of the above.

I should have a bit more flexibility this summer to support, if I can be helpful.

**Comment by JWiley** [comment]
@jwilliamrozelle No problem. Over summer if you've got some time, please reach out & would love any contributions.
