### ISSUE TITLE
Random-Effect Integration for Factors

### ISSUE THREAD

**Issue by thisisnickb** [JWiley/brmsmargins#5]
Hello,

I'm having a bit of trouble getting random-effect integration to produce marginal sigma effects when the key predictor is a factor. Things work just fine when I ask for just the fixed effects, but they break for the more complex case.

A reproducible example is below:

dmixed <- withr::with_seed(
  seed = 12345, code = {
    nGroups <- 100
    nObs <- 20
    theta.location <- matrix(rnorm(nGroups * 2), nrow = nGroups, ncol = 2)
    theta.location[, 1] <- theta.location[, 1] - mean(theta.location[, 1])
    theta.location[, 2] <- theta.location[, 2] - mean(theta.location[, 2])
    theta.location[, 1] <- theta.location[, 1] / sd(theta.location[, 1])
    theta.location[, 2] <- theta.location[, 2] / sd(theta.location[, 2])
    theta.location <- theta.location %*% chol(matrix(c(1.5, -.25, -.25, .5^2), 2))
    theta.location[, 1] <- theta.location[, 1] - 2.5
    theta.location[, 2] <- theta.location[, 2] + 1
    dmixed <- data.table::data.table(
      x = rep(rep(0:1, each = nObs / 2), times = nGroups))
    dmixed[, ID := rep(seq_len(nGroups), each = nObs)]
    
    for (i in seq_len(nGroups)) {
      dmixed[ID == i, y := rnorm(
        n = nObs,
        mean = theta.location[i, 1] + theta.location[i, 2] * x,
        sd = exp(1 + theta.location[i, 1] + theta.location[i, 2] * x))
      ]
    }
    data.table::copy(dmixed)
  })

#Making 'x' into a factor#
dmixed$x<-factor(dmixed$x)

ls.me <- bf(y ~ 1 + x + (1+x|ID),
            sigma ~ 1 + x + (1+x|ID))
ls.me_out <- brm(ls.me,
                 data = dmixed,
                 chains = 4, cores = 8, iter = 5000, control = list(adapt_delta = .85, max_treedepth = 15),
                 seed = 7766, save_all_pars = T)

#This seems to work#
ame2b.lsme.f <- brmsmargins(
  ls.me_out,
  at = data.frame(x = c("0", "1")),
  contrasts = cbind("AME x" = c(-1, 1)),
  dpar = "sigma",
  effects = "fixed", k = 100L, seed = 1234)

#This does not seem to work#
ame2b.lsme.i <- brmsmargins(
  ls.me_out,
  at = data.frame(x = c("0", "1")),
  contrasts = cbind("AME x" = c(-1, 1)),
  dpar = "sigma",
  effects = "integrateoutRE", k = 100L, seed = 1234)

**Comment by JWiley** [comment]
@thisisnickb I believe this is working now?  In the development version from GitHub, I get:

```r
devtools::install_github("JWiley/brmsmargins")
```

```r
ame2b.lsme.f$ContrastSummary
##           M       Mdn        LL        UL PercentROPE PercentMID   CI CIType
##1: 0.3778774 0.3752412 0.2613803 0.5106025          NA         NA 0.99    HDI
##   ROPE  MID Label
##1: <NA> <NA> AME x
```

and


```r
ame2b.lsme.i$ContrastSummary
##           M       Mdn        LL       UL PercentROPE PercentMID   CI CIType
##1: 0.7109005 0.6774026 0.3050286 1.339695          NA         NA 0.99    HDI
##   ROPE  MID Label
##1: <NA> <NA> AME x
```

Based on the simulated values, the true mean SD is `0.7730968`  so the AME here when integrating over random effects is quite close and certainly the uncertainty interval includes the true value so I think it is working?  Would you have a check and let me know?

**Comment by JWiley** [comment]
It all seems to be working in v0.2.0 as far as I can tell.  Closing for now but can reopen if the issue remains.
